Fix [Vehicle Spawn #115] + Fix dropPoint to Default to spawn or coords
Qbox-project/qbx_garages pull request #120
Opened 2024-08-15 18:57 UTC by RoyaleWind

## Description

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-08-15 19:25 UTC, mafewtm commented on client/main.lua
> +        accessPoint.dropPoint = (accessPoint.dropPoint == nil) and accessPoint.spawn or accessPoint.dropPoint
```suggestion
        accessPoint.dropPoint = accessPoint.dropPoint or accessPoint.spawn
```

2024-08-15 23:03 UTC, mafewtm commented on server/spawn-vehicle.lua
> +    local spawnCoords = accessPoint.spawn or accessPoint.coords
the spawnCoords variable is defined both here and line 42

2024-08-15 23:09 UTC, mafewtm commented on server/spawn-vehicle.lua
> +
```suggestion
    local nearbyVehicle = lib.getClosestVehicle(vec3(spawnCoords.x,spawnCoords.y,spawnCoords.z), 5.0, false)

    if nearbyVehicle then
        exports.qbx_core:Notify(source, locale('error.no_space'), 'error')
        return
    end
```

2024-08-16 07:14 UTC, solareon requested changes

2024-08-16 07:14 UTC, solareon commented on server/spawn-vehicle.lua
> +    local nearbyVehicle = lib.getClosestVehicle(vec3(spawnCoords.x, spawnCoords.y, spawnCoords.z), 5.0, false)
Can you pull the distance check variable out to the config. Depending on where folks place these spots 5.0 might not work for them.

2024-08-16 13:18 UTC, solareon approved these changes

2024-08-16 13:18 UTC, solareon commented on config/server.lua
> +    distanceCheck = 5.0, -- The distance that needs to bee clear to let the vehicle spawn, this prevents staking
```suggestion
    distanceCheck = 5.0, -- The distance that needs to bee clear to let the vehicle spawn, this prevents vehicles stacking on top of each other
```

2024-08-16 13:55 UTC, Manason approved these changes

2024-08-16 13:56 UTC, merged